---
- name: Install and configure Nginx
  hosts: all
  become: yes

  tasks:
    - name: Update ubuntu server
      apt:
        update_cache: yes

    - name: Update all packages
      apt:
        upgrade: dist

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Remove the existing var/www/html
      command: rm -rf /var/www/html

    - name: Git clone the repository
      git:
        repo: "{{ repo_url }}/{{ repo }}.git"
        dest: /var/www/html
        version: development
        accept_hostkey: yes

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted